// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjVNYQTJlD4RZnWmltx1FkJGZ7yccObKE',
    appId: '1:956701068394:web:a97ce4863dee7430eb0e13',
    messagingSenderId: '956701068394',
    projectId: 'traffictracking-a103e',
    authDomain: 'traffictracking-a103e.firebaseapp.com',
    storageBucket: 'traffictracking-a103e.appspot.com',
    measurementId: 'G-2JDHP5WFGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArSoK9Wx9Hpe1R9ZywuLEIMVjCtHjO8Os',
    appId: '1:956701068394:android:92d6cbc4f5e51c30eb0e13',
    messagingSenderId: '956701068394',
    projectId: 'traffictracking-a103e',
    storageBucket: 'traffictracking-a103e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVruIscsWvBDD-kMD5x9DhStaeVgHDPMg',
    appId: '1:956701068394:ios:4797fa0bfa5e0523eb0e13',
    messagingSenderId: '956701068394',
    projectId: 'traffictracking-a103e',
    storageBucket: 'traffictracking-a103e.appspot.com',
    iosClientId: '956701068394-kc76355p8ej903a2u7ubpafmct56dkmt.apps.googleusercontent.com',
    iosBundleId: 'com.example.doAn1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVruIscsWvBDD-kMD5x9DhStaeVgHDPMg',
    appId: '1:956701068394:ios:b7c24d021f7be70ceb0e13',
    messagingSenderId: '956701068394',
    projectId: 'traffictracking-a103e',
    storageBucket: 'traffictracking-a103e.appspot.com',
    iosClientId: '956701068394-3c9cl78rfeq7e6ae5iafkn5p9im45b3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.doAn1.RunnerTests',
  );
}
